/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppStyleRouteImport } from './routes/app.style'
import { Route as AppResultRouteImport } from './routes/app.result'
import { Route as AppLoadingRouteImport } from './routes/app.loading'
import { Route as ApiHairstyleStatusRouteImport } from './routes/api/hairstyle-status'
import { Route as ApiHairstyleRouteImport } from './routes/api/hairstyle'
import { Route as ApiAccessLoginRouteImport } from './routes/api/access-login'
import { Route as ApiAccessCheckRouteImport } from './routes/api/access-check'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStyleRoute = AppStyleRouteImport.update({
  id: '/app/style',
  path: '/app/style',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResultRoute = AppResultRouteImport.update({
  id: '/app/result',
  path: '/app/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoadingRoute = AppLoadingRouteImport.update({
  id: '/app/loading',
  path: '/app/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHairstyleStatusRoute = ApiHairstyleStatusRouteImport.update({
  id: '/api/hairstyle-status',
  path: '/api/hairstyle-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHairstyleRoute = ApiHairstyleRouteImport.update({
  id: '/api/hairstyle',
  path: '/api/hairstyle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessLoginRoute = ApiAccessLoginRouteImport.update({
  id: '/api/access-login',
  path: '/api/access-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessCheckRoute = ApiAccessCheckRouteImport.update({
  id: '/api/access-check',
  path: '/api/access-check',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/access-check': typeof ApiAccessCheckRoute
  '/api/access-login': typeof ApiAccessLoginRoute
  '/api/hairstyle': typeof ApiHairstyleRoute
  '/api/hairstyle-status': typeof ApiHairstyleStatusRoute
  '/app/loading': typeof AppLoadingRoute
  '/app/result': typeof AppResultRoute
  '/app/style': typeof AppStyleRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/access-check': typeof ApiAccessCheckRoute
  '/api/access-login': typeof ApiAccessLoginRoute
  '/api/hairstyle': typeof ApiHairstyleRoute
  '/api/hairstyle-status': typeof ApiHairstyleStatusRoute
  '/app/loading': typeof AppLoadingRoute
  '/app/result': typeof AppResultRoute
  '/app/style': typeof AppStyleRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/access-check': typeof ApiAccessCheckRoute
  '/api/access-login': typeof ApiAccessLoginRoute
  '/api/hairstyle': typeof ApiHairstyleRoute
  '/api/hairstyle-status': typeof ApiHairstyleStatusRoute
  '/app/loading': typeof AppLoadingRoute
  '/app/result': typeof AppResultRoute
  '/app/style': typeof AppStyleRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/api/access-check'
    | '/api/access-login'
    | '/api/hairstyle'
    | '/api/hairstyle-status'
    | '/app/loading'
    | '/app/result'
    | '/app/style'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/api/access-check'
    | '/api/access-login'
    | '/api/hairstyle'
    | '/api/hairstyle-status'
    | '/app/loading'
    | '/app/result'
    | '/app/style'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/api/access-check'
    | '/api/access-login'
    | '/api/hairstyle'
    | '/api/hairstyle-status'
    | '/app/loading'
    | '/app/result'
    | '/app/style'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAccessCheckRoute: typeof ApiAccessCheckRoute
  ApiAccessLoginRoute: typeof ApiAccessLoginRoute
  ApiHairstyleRoute: typeof ApiHairstyleRoute
  ApiHairstyleStatusRoute: typeof ApiHairstyleStatusRoute
  AppLoadingRoute: typeof AppLoadingRoute
  AppResultRoute: typeof AppResultRoute
  AppStyleRoute: typeof AppStyleRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/style': {
      id: '/app/style'
      path: '/app/style'
      fullPath: '/app/style'
      preLoaderRoute: typeof AppStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/result': {
      id: '/app/result'
      path: '/app/result'
      fullPath: '/app/result'
      preLoaderRoute: typeof AppResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/loading': {
      id: '/app/loading'
      path: '/app/loading'
      fullPath: '/app/loading'
      preLoaderRoute: typeof AppLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hairstyle-status': {
      id: '/api/hairstyle-status'
      path: '/api/hairstyle-status'
      fullPath: '/api/hairstyle-status'
      preLoaderRoute: typeof ApiHairstyleStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hairstyle': {
      id: '/api/hairstyle'
      path: '/api/hairstyle'
      fullPath: '/api/hairstyle'
      preLoaderRoute: typeof ApiHairstyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access-login': {
      id: '/api/access-login'
      path: '/api/access-login'
      fullPath: '/api/access-login'
      preLoaderRoute: typeof ApiAccessLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access-check': {
      id: '/api/access-check'
      path: '/api/access-check'
      fullPath: '/api/access-check'
      preLoaderRoute: typeof ApiAccessCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAccessCheckRoute: ApiAccessCheckRoute,
  ApiAccessLoginRoute: ApiAccessLoginRoute,
  ApiHairstyleRoute: ApiHairstyleRoute,
  ApiHairstyleStatusRoute: ApiHairstyleStatusRoute,
  AppLoadingRoute: AppLoadingRoute,
  AppResultRoute: AppResultRoute,
  AppStyleRoute: AppStyleRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
